### ISSUE TITLE
[DEV] Raspberry PI에서 오디오 파일을 서버로 전송하는 Task의 향상

### ISSUE THREAD

**Issue by minusmo** [GDSC-CAU/AudioPoli-HW#8]
## Summary
- HTTP/1.1을 이용한 POST 방식의 메시지 PUSH Task의 Enhancement
- Integer로의 type casting operation의 Enhancement
- Audio Recording Task의 Enhancement

## Description
- 현재 HTTP/1.1 POST 방식으로 메시지를 전달하며, Content-Type이 x-www-form-urlencoded인 것으로 보입니다.
따라서 바이너리 오디오 파일을 읽어와서 base64 encoding을 거치는 것으로 생각되는데요, 제 생각에는, 
오디오 파일을 그냥 읽어와서 인코딩하지 않고 multipart/form-data로 넘기는 것이 좋지 않나 합니다.
이렇게 하면 인코딩하는 리소스가 들지 않을 뿐더러 명시적으로 서버에서 FILE로 받을 수 있습니다.
만약 오디오 파일만 전송해야 한다면, audio 혹은 octet-stream 타입으로 전송하는 방법도 가능하고,
압축 전송을 한다면 transmission time gain이 있을 것입니다. 
테스트는 로컬에서해서 빠르지만, 실제 network를 탄다면 용량이 큰 바이너리 파일의 전송 지연을 고려해야합니다.

- app.py 66번째 줄에서 int()로 캐스팅하는 것이 있는데요, 컴퓨팅 리소스가 부족해 보이지는 않지만 이 디바이스가 수행해야하는 작업의 특성을 고려할 때, performance가 중요할 것으로 생각되어 32-bit 정수로 변환하는 operation을 bitwise operation으로 하는 것은 어떨까 합니다. Bitwise operation은 다음과 같이 할 수 있습니다. `(fs *2) and 0xFFFFFFFF`. 현저하진 않지만 분명한 performance gain이 있습니다.

- Busy하게 FILE I/O를 하고 있는데요, 가능하면 입출력 없이 main memory에서만 파일을 전송하는 것도 나쁘지 않나... 생각이 듭니다.
파일이 50mb 정도로 큰데 read/write 작업을 하는 것은 부담이니까요.

> 
> 당장 문제는 없어보이니 나중에 고려해서 도움이 될 것 같다면 반영한다면 좋겠습니다.
> 도움이 되기를 바랍니다.(제가 말한 것이 꼭 문제가 아닐 수도, 옳지 않을 수도 있습니다.)

---

**Comment by minseok128** [comment]
정성스러운 조언 감사합니다. 확인하고 꼭 반영해보겠습니다! 🥳
